
<OverviewScreen>:
    name: 'overview_screen'

    BoxLayout:
        orientation: 'vertical'
        padding: [5,5]
        spacing: 10
        MDLabel:
            text: 'Inicio'
            halign: 'center'
            font_style: 'H4'
        MDLabel:
            text: 'Resumen del dia'
            halign: 'center'
            font_style: 'H4'
        
                

            
    
                
        